apiVersion: 1
datasources:
  - name: clickhouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse
      username: default
      tlsSkipVerify: false
    secureJsonData:
      password: ""