FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}
SQLALCHEMY_DATABASE_URI = 'sqlite:////data/superset.db'
ENABLE_PROXY_FIX = True
SECRET_KEY = "/MVYGuY9CPCMYboKFIROBVTWcJ069z1y+SsjWFAMZpZ00b+I9lILq0CM"